services:
  - type: web
    name: me-api-playground
    env: node
    buildCommand: npm install && npm run seed
    startCommand: npm start
    plan: free
    autoDeploy: true
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
