services:
  - type: web
    name: me-api-playground
    env: node
    plan: free
    autoDeploy: true
    buildCommand: npm install && npm run seed
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_DIALECT
        value: sqlite
