name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Rebuild native dependencies
      run: npm rebuild sqlite3
    
    - name: Create data directory
      run: mkdir -p data
    
    - name: Seed database
      run: npm run seed
    
    - name: Start server in background
      run: |
        npm start &
        sleep 5
    
    - name: Test health endpoint
      run: |
        curl -f http://localhost:3000/health || exit 1
    
    - name: Test API endpoints
      run: |
        curl -f http://localhost:3000/api/profile || exit 1
        curl -f "http://localhost:3000/api/projects?skill=JavaScript" || exit 1
        curl -f http://localhost:3000/api/skills/top || exit 1
        curl -f "http://localhost:3000/api/search?q=cpu" || exit 1
    
    - name: Stop server
      run: pkill -f "node index.js" || true
